name: Yuanshen auto-signin

on:
  schedule:
  - cron: '0 0 * * *'
  
  workflow_dispatch:

jobs:

  run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: therebefor/genshinhelper2
        path: genshinhelper2
        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r genshinhelper2/requirements.txt
        
    - name: Run genshinhelper
      env:
        COOKIES: ${{ secrets.COOKIES }} 
      run: |
        python genshinhelper2/setup.py install
